// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const getAllDocuments = `-- name: GetAllDocuments :many
SELECT id, name FROM documents
`

func (q *Queries) GetAllDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, getAllDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
